[package]
name = "cplang"
version = "0.1.0"
edition = "2024"

[dependencies]
test_derive = { path = "src/test_derive" }

[profile.release]
lto = false
opt-level = "z"
panic = "abort"
strip = "symbols"

